network:
  name: vit-b-16
  model: openood/networks/vit_b_16.py   #  vit-base-p16-384.py
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False         # set 'True' to load pretrained model  True
  checkpoint: none         # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
dataset:
  image_size: 224  # 384
ood_dataset:
  image_size: 224  # 384
