exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'_lam'@{trainer.lambda_oe}'_'@{mark}'-1/s'@{seed}'"
output_dir: ./results/
save_output: True
merge_option: default
mark: default
seed: 1024
pipeline:
  name: train_oe

num_gpus: 1
num_workers: 8
num_machines: 1
machine_rank: 0

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0005

trainer:
  name: oe
  lambda_oe: 0.5
